# Generated by Django 5.0.7 on 2025-10-28 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('country', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('address', models.TextField(blank=True, verbose_name='Dirección Completa')),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='Posición Actual')),
                ('current_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa Actual')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='Años de Experiencia')),
                ('education_level', models.CharField(max_length=100, verbose_name='Nivel de Estudios')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Universidad')),
                ('degree', models.CharField(blank=True, max_length=200, verbose_name='Carrera/Título')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Lista de habilidades del candidato', verbose_name='Habilidades')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Lista de idiomas con nivel', verbose_name='Idiomas')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Lista de certificaciones', verbose_name='Certificaciones')),
                ('salary_expectation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expectativa Salarial Mínima')),
                ('salary_expectation_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expectativa Salarial Máxima')),
                ('salary_currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('screening', 'En Revisión'), ('qualified', 'Calificado'), ('interview', 'En Entrevista'), ('offer', 'Oferta Extendida'), ('hired', 'Contratado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], default='new', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(blank=True, help_text='Ej: LinkedIn, Portal de empleo, Referido, etc.', max_length=100, verbose_name='Fuente de Reclutamiento')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumen generado por IA')),
                ('ai_match_score', models.IntegerField(blank=True, help_text='Puntuación de 0 a 100', null=True, verbose_name='Puntuación de Coincidencia IA')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Análisis detallado generado por IA', verbose_name='Análisis Completo de IA')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Disponible desde')),
                ('notice_period_days', models.IntegerField(blank=True, null=True, verbose_name='Días de Preaviso')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portafolio')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'Curriculum Vitae'), ('cover_letter', 'Carta de Presentación'), ('certificate', 'Certificado'), ('portfolio', 'Portafolio'), ('other', 'Otro')], default='cv', max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='candidates/%Y/%m/', verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('ai_extracted_text', models.TextField(blank=True, verbose_name='Texto Extraído por IA')),
                ('ai_parsed_data', models.JSONField(blank=True, default=dict, help_text='Información estructurada extraída del CV', verbose_name='Datos Parseados por IA')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate', verbose_name='Candidato')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento del Candidato',
                'verbose_name_plural': 'Documentos de Candidatos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('is_important', models.BooleanField(default=False, verbose_name='Nota Importante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate', verbose_name='Candidato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota del Candidato',
                'verbose_name_plural': 'Notas de Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Aplicó'), ('screening', 'En Revisión'), ('shortlisted', 'Pre-seleccionado'), ('interview_scheduled', 'Entrevista Agendada'), ('interviewed', 'Entrevistado'), ('offered', 'Oferta Extendida'), ('accepted', 'Oferta Aceptada'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], default='applied', max_length=30, verbose_name='Estado de la Aplicación')),
                ('match_percentage', models.IntegerField(blank=True, help_text='0-100', null=True, verbose_name='Porcentaje de Coincidencia')),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 - 5.00', max_digits=3, null=True, verbose_name='Calificación General')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de Rechazo')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aplicación')),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrevista')),
                ('offer_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Oferta')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='candidates.candidate', verbose_name='Candidato')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_candidates', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Aplicación de Candidato',
                'verbose_name_plural': 'Aplicaciones de Candidatos',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='profiles',
            field=models.ManyToManyField(related_name='candidates', through='candidates.CandidateProfile', to='profiles.profile', verbose_name='Perfiles'),
        ),
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'Nuevo'), ('screening', 'En Revisión'), ('qualified', 'Calificado'), ('interview', 'En Entrevista'), ('offer', 'Oferta Extendida'), ('hired', 'Contratado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], max_length=20, verbose_name='Estado Anterior')),
                ('to_status', models.CharField(choices=[('new', 'Nuevo'), ('screening', 'En Revisión'), ('qualified', 'Calificado'), ('interview', 'En Entrevista'), ('offer', 'Oferta Extendida'), ('hired', 'Contratado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], max_length=20, verbose_name='Estado Nuevo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='candidates.candidate', verbose_name='Candidato')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
            ],
            options={
                'verbose_name': 'Historial de Estado del Candidato',
                'verbose_name_plural': 'Historial de Estados de Candidatos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates__email_188e48_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status'], name='candidates__status_0f124f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='candidates__created_d94c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name', 'first_name'], name='candidates__last_na_35ea62_idx'),
        ),
    ]
