# Generated by Django 5.0.7 on 2025-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Carga Masiva de CVs',
                'verbose_name_plural': 'Carga Masiva de CVs',
                'managed': False,
            },
        ),
    ]
