# Generated by Django 5.0.7 on 2025-10-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200, verbose_name='Título de la Posición')),
                ('position_description', models.TextField(verbose_name='Descripción de la Posición')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('location_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('location_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Trabajo Remoto')),
                ('is_hybrid', models.BooleanField(default=False, verbose_name='Trabajo Híbrido')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Máximo')),
                ('salary_currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('salary_period', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20, verbose_name='Periodo de Pago')),
                ('education_level', models.CharField(max_length=100, verbose_name='Nivel de Estudios')),
                ('years_experience', models.IntegerField(verbose_name='Años de Experiencia Requeridos')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='Edad Máxima')),
                ('technical_skills', models.JSONField(blank=True, default=list, help_text='Lista de habilidades técnicas requeridas', verbose_name='Habilidades Técnicas')),
                ('soft_skills', models.JSONField(blank=True, default=list, help_text='Lista de competencias blandas requeridas', verbose_name='Habilidades Blandas')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Lista de idiomas requeridos con nivel', verbose_name='Idiomas')),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficios')),
                ('additional_requirements', models.TextField(blank=True, verbose_name='Requisitos Adicionales')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('in_progress', 'En Proceso'), ('candidates_found', 'Candidatos Encontrados'), ('in_evaluation', 'En Evaluación'), ('in_interview', 'En Entrevistas'), ('finalists', 'Finalistas'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=30, verbose_name='Estado')),
                ('service_type', models.CharField(choices=[('normal', 'Servicio Normal'), ('specialized', 'Servicio Especializado')], default='normal', max_length=20, verbose_name='Tipo de Servicio')),
                ('number_of_positions', models.IntegerField(default=1, verbose_name='Número de Posiciones')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('desired_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Deseada de Inicio')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('meeting_transcription', models.TextField(blank=True, verbose_name='Transcripción de la Reunión')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('client_approved', models.BooleanField(default=False, verbose_name='Aprobado por Cliente')),
                ('client_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación del Cliente')),
                ('client_feedback', models.TextField(blank=True, verbose_name='Retroalimentación del Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Perfil de Reclutamiento',
                'verbose_name_plural': 'Perfiles de Reclutamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('profile_pdf', 'PDF del Perfil'), ('client_approval', 'Aprobación del Cliente'), ('meeting_notes', 'Notas de Reunión'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='profiles/%Y/%m/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.profile', verbose_name='Perfil')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento del Perfil',
                'verbose_name_plural': 'Documentos de Perfiles',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('in_progress', 'En Proceso'), ('candidates_found', 'Candidatos Encontrados'), ('in_evaluation', 'En Evaluación'), ('in_interview', 'En Entrevistas'), ('finalists', 'Finalistas'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], max_length=30, verbose_name='Estado Anterior')),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('in_progress', 'En Proceso'), ('candidates_found', 'Candidatos Encontrados'), ('in_evaluation', 'En Evaluación'), ('in_interview', 'En Entrevistas'), ('finalists', 'Finalistas'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], max_length=30, verbose_name='Estado Nuevo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status'], name='profiles_pr_status_2735dc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['client'], name='profiles_pr_client__6f8776_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['position_title'], name='profiles_pr_positio_107f52_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created_at'], name='profiles_pr_created_86c7cf_idx'),
        ),
    ]
