# Generated by Django 5.0.7 on 2025-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published_platforms',
            field=models.JSONField(blank=True, default=list, help_text='Lista de plataformas donde se ha publicado el perfil. Solo disponible cuando el estado es "En Proceso"', verbose_name='Plataformas de Publicación'),
        ),
    ]
