# Generated by Django 5.0.7 on 2025-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_published_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='published_platforms',
            field=models.JSONField(blank=True, default=list, help_text="Plataformas donde se publicará: ['LinkedIn', 'Indeed', 'OCC']"),
        ),
    ]
