# Generated by Django 5.0.7 on 2025-11-04 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Sección')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('available_variables', models.JSONField(blank=True, default=list, verbose_name='Variables Disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Sección de Documento',
                'verbose_name_plural': 'Secciones de Documentos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('document_type', models.CharField(choices=[('profile', 'Perfil de Reclutamiento'), ('candidate_report', 'Reporte de Candidato'), ('comparison', 'Comparación de Candidatos'), ('final_report', 'Reporte Final'), ('client_report', 'Reporte para Cliente'), ('custom', 'Personalizado')], default='custom', max_length=50, verbose_name='Tipo de Documento')),
                ('header_text', models.CharField(blank=True, max_length=200, verbose_name='Texto del Encabezado')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='Texto del Pie de Página')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='templates/logos/', verbose_name='Logo de la Empresa')),
                ('style_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de Estilo')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='Secciones del Documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Datos Personalizados')),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/', verbose_name='Archivo PDF')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño del Archivo (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('generation_time', models.FloatField(default=0, verbose_name='Tiempo de Generación (segundos)')),
                ('download_count', models.IntegerField(default=0, verbose_name='Número de Descargas')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Descarga')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='candidates.candidate', verbose_name='Candidato Relacionado')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.generateddocument', verbose_name='Documento Padre')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='profiles.profile', verbose_name='Perfil Relacionado')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.documenttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Documento Generado',
                'verbose_name_plural': 'Documentos Generados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generado'), ('downloaded', 'Descargado'), ('shared', 'Compartido'), ('deleted', 'Eliminado'), ('regenerated', 'Regenerado')], max_length=20, verbose_name='Acción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.generateddocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Log de Documento',
                'verbose_name_plural': 'Logs de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['document_type', 'is_active'], name='documents_d_documen_329e75_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_default'], name='documents_d_is_defa_7699cf_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['status'], name='documents_g_status_352d42_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['profile'], name='documents_g_profile_ad06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['candidate'], name='documents_g_candida_6e4628_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['generated_by', '-created_at'], name='documents_g_generat_39e0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['-created_at'], name='documents_g_created_bb89b4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlog',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_5f6c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlog',
            index=models.Index(fields=['action'], name='documents_d_action_55adea_idx'),
        ),
    ]
