# Generated by Django 5.0.7 on 2025-11-04 04:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('reviewed', 'Revisada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='estado')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asignación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha límite para completar la evaluación', null=True, verbose_name='fecha de expiración')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación calculada automáticamente', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='puntuación automática')),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación ajustada por el evaluador', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='puntuación manual')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='puntuación final')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='aprobado')),
                ('evaluator_comments', models.TextField(blank=True, help_text='Comentarios y retroalimentación para el candidato', verbose_name='comentarios del evaluador')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas no visibles para el candidato', verbose_name='notas internas')),
                ('time_taken_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='tiempo tomado (minutos)')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='asignado por')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='candidates.candidate', verbose_name='candidato')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'evaluación de candidato',
                'verbose_name_plural': 'evaluaciones de candidatos',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('is_internal', models.BooleanField(default=False, help_text='Si es visible solo internamente', verbose_name='es interno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evaluations.candidateevaluation', verbose_name='evaluación')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_comments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'comentario de evaluación',
                'verbose_name_plural': 'comentarios de evaluación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la evaluación (ej: "Evaluación Python Senior")', max_length=200, verbose_name='título')),
                ('description', models.TextField(help_text='Descripción detallada del propósito de esta evaluación', verbose_name='descripción')),
                ('category', models.CharField(choices=[('technical', 'Técnica'), ('soft_skills', 'Habilidades Blandas'), ('leadership', 'Liderazgo'), ('cultural_fit', 'Ajuste Cultural'), ('language', 'Idiomas'), ('other', 'Otro')], default='technical', max_length=20, verbose_name='categoría')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Tiempo estimado para completar la evaluación', verbose_name='duración (minutos)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, help_text='Puntuación mínima para aprobar (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='puntuación mínima')),
                ('is_active', models.BooleanField(default=True, help_text='Si está disponible para ser asignada', verbose_name='activa')),
                ('is_template', models.BooleanField(default=True, help_text='Si es una plantilla reutilizable o evaluación única', verbose_name='es plantilla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_templates', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('profile', models.ForeignKey(blank=True, help_text='Perfil de reclutamiento asociado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_templates', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'plantilla de evaluación',
                'verbose_name_plural': 'plantillas de evaluación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='El texto de la pregunta', verbose_name='pregunta')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso'), ('short_text', 'Texto Corto'), ('long_text', 'Texto Largo'), ('scale', 'Escala (1-10)'), ('code', 'Código'), ('file_upload', 'Subir Archivo')], default='multiple_choice', max_length=20, verbose_name='tipo de pregunta')),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de opciones para preguntas de opción múltiple. Ejemplo: ["Opción A", "Opción B"]', verbose_name='opciones')),
                ('correct_answer', models.JSONField(blank=True, help_text='Respuesta correcta o lista de respuestas correctas para auto-calificación', null=True, verbose_name='respuesta correcta')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, help_text='Puntos que vale esta pregunta', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='puntos')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la evaluación', verbose_name='orden')),
                ('help_text', models.TextField(blank=True, help_text='Instrucciones o aclaraciones adicionales para el candidato', verbose_name='texto de ayuda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluationtemplate', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'pregunta de evaluación',
                'verbose_name_plural': 'preguntas de evaluación',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.evaluationtemplate', verbose_name='plantilla'),
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Respuesta en texto del candidato', verbose_name='respuesta')),
                ('selected_option', models.CharField(blank=True, help_text='Para preguntas de opción múltiple', max_length=500, verbose_name='opción seleccionada')),
                ('scale_value', models.PositiveIntegerField(blank=True, help_text='Para preguntas de escala 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='valor de escala')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='evaluations/answers/%Y/%m/', verbose_name='archivo subido')),
                ('is_correct', models.BooleanField(blank=True, help_text='Si la respuesta es correcta (para auto-calificación)', null=True, verbose_name='es correcta')),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='puntos obtenidos')),
                ('feedback', models.TextField(blank=True, help_text='Comentarios del evaluador sobre esta respuesta', verbose_name='retroalimentación')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de respuesta')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.candidateevaluation', verbose_name='evaluación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.evaluationquestion', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'respuesta de evaluación',
                'verbose_name_plural': 'respuestas de evaluación',
                'ordering': ['evaluation', 'question__order'],
                'indexes': [models.Index(fields=['evaluation', 'question'], name='evaluations_evaluat_2e5922_idx')],
                'unique_together': {('evaluation', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='evaluationtemplate',
            index=models.Index(fields=['category', 'is_active'], name='evaluations_categor_012923_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationtemplate',
            index=models.Index(fields=['created_at'], name='evaluations_created_383509_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['template', 'order'], name='evaluations_templat_f7b15c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevaluation',
            index=models.Index(fields=['status', 'assigned_at'], name='evaluations_status_bf53b0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevaluation',
            index=models.Index(fields=['candidate', 'status'], name='evaluations_candida_919993_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevaluation',
            index=models.Index(fields=['template'], name='evaluations_templat_b6e6a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateevaluation',
            unique_together={('candidate', 'template', 'assigned_at')},
        ),
    ]
