# Generated by Django 5.0.7 on 2025-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtemplate',
            name='share_token',
            field=models.CharField(blank=True, help_text='Token único para compartir la evaluación públicamente', max_length=255, null=True, unique=True, verbose_name='token de compartir'),
        ),
    ]
