# Generated by Django 5.0.7 on 2025-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationtemplate_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso'), ('short_text', 'Texto Corto'), ('short_answer', 'Respuesta Corta'), ('long_text', 'Texto Largo'), ('essay', 'Ensayo'), ('scale', 'Escala (1-10)'), ('rating', 'Calificación (1-5)'), ('code', 'Código'), ('file_upload', 'Subir Archivo')], default='multiple_choice', max_length=20, verbose_name='tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='evaluationtemplate',
            name='category',
            field=models.CharField(choices=[('technical', 'Técnica'), ('behavioral', 'Conductual'), ('cognitive', 'Cognitiva'), ('soft_skills', 'Habilidades Blandas'), ('leadership', 'Liderazgo'), ('cultural_fit', 'Ajuste Cultural'), ('cultural', 'Cultural Fit'), ('language', 'Idiomas'), ('other', 'Otro')], default='technical', max_length=20, verbose_name='categoría'),
        ),
    ]
