# Generated by Django 5.0.7 on 2025-10-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('industry', models.CharField(max_length=100, verbose_name='Industria/Sector')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre del Contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('contact_position', models.CharField(max_length=100, verbose_name='Puesto')),
                ('address_street', models.CharField(max_length=200, verbose_name='Calle')),
                ('address_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('address_zip', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('address_country', models.CharField(default='México', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
