# Generated by Django 5.0.7 on 2025-10-30 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.TextField(help_text='Se almacena de forma segura', verbose_name='API Key (Encriptada)')),
                ('default_model', models.CharField(default='claude-3-opus-20240229', max_length=100, verbose_name='Modelo Predeterminado')),
                ('max_tokens_per_request', models.IntegerField(default=4000, verbose_name='Máximo de Tokens por Solicitud')),
                ('daily_token_limit', models.IntegerField(default=1000000, verbose_name='Límite Diario de Tokens')),
                ('tokens_used_today', models.IntegerField(default=0, verbose_name='Tokens Usados Hoy')),
                ('last_reset_date', models.DateField(auto_now_add=True, verbose_name='Fecha del Último Reset')),
                ('auto_analyze_cvs', models.BooleanField(default=True, verbose_name='Analizar CVs Automáticamente')),
                ('auto_generate_profiles', models.BooleanField(default=False, verbose_name='Generar Perfiles Automáticamente')),
                ('auto_match_candidates', models.BooleanField(default=True, verbose_name='Match Automático de Candidatos')),
                ('enable_async_processing', models.BooleanField(default=True, verbose_name='Procesamiento Asíncrono (Celery)')),
                ('retry_on_failure', models.BooleanField(default=True, verbose_name='Reintentar en Caso de Fallo')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máximo de Reintentos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuración de IA',
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plantilla')),
                ('analysis_type', models.CharField(choices=[('transcription', 'Transcripción de Reunión'), ('cv_parsing', 'Análisis de CV'), ('profile_generation', 'Generación de Perfil'), ('candidate_matching', 'Matching de Candidatos'), ('evaluation_generation', 'Generación de Evaluación')], max_length=50, verbose_name='Tipo de Análisis')),
                ('prompt_template', models.TextField(help_text='Use {variables} para valores dinámicos', verbose_name='Plantilla del Prompt')),
                ('system_message', models.TextField(blank=True, help_text='Instrucciones del sistema para Claude', verbose_name='Mensaje del Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('max_tokens', models.IntegerField(default=4000, verbose_name='Máximo de Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 = más determinístico, 1.0 = más creativo', verbose_name='Temperatura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Prompt',
                'verbose_name_plural': 'Plantillas de Prompts',
                'ordering': ['analysis_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('transcription', 'Transcripción de Reunión'), ('cv_parsing', 'Análisis de CV'), ('profile_generation', 'Generación de Perfil'), ('candidate_matching', 'Matching de Candidatos'), ('evaluation_generation', 'Generación de Evaluación')], max_length=50, verbose_name='Tipo de Análisis')),
                ('input_data', models.JSONField(help_text='Datos enviados a Claude API', verbose_name='Datos de Entrada')),
                ('output_data', models.JSONField(help_text='Respuesta de Claude API', verbose_name='Resultado del Análisis')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens Utilizados')),
                ('processing_time', models.FloatField(default=0, help_text='Tiempo en segundos que tomó el análisis', verbose_name='Tiempo de Procesamiento (segundos)')),
                ('model_used', models.CharField(default='claude-3-opus-20240229', max_length=100, verbose_name='Modelo de IA Utilizado')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='candidates.candidate', verbose_name='Candidato Relacionado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='profiles.profile', verbose_name='Perfil Relacionado')),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analysis_type'], name='ai_services_analysi_9cfb2c_idx'), models.Index(fields=['-created_at'], name='ai_services_created_a9ecdb_idx'), models.Index(fields=['profile'], name='ai_services_profile_10dc8a_idx'), models.Index(fields=['candidate'], name='ai_services_candida_fe2d5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cv_analysis', 'Análisis de CV'), ('matching', 'Matching'), ('profile_generation', 'Generación de Perfil'), ('summarization', 'Resumen de Candidato')], max_length=50)),
                ('prompt', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('model_used', models.CharField(blank=True, default='claude-3-sonnet-20240229', max_length=100)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='candidates.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='ai_services_action_163c1d_idx'), models.Index(fields=['-created_at'], name='ai_services_created_7ac9d5_idx'), models.Index(fields=['candidate'], name='ai_services_candida_ce5414_idx'), models.Index(fields=['profile'], name='ai_services_profile_c3e298_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfileMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('technical_skills_score', models.IntegerField(default=0)),
                ('soft_skills_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('location_score', models.IntegerField(default=0)),
                ('salary_score', models.IntegerField(default=0)),
                ('matching_analysis', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='candidates.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchings_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='profiles.profile')),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
                'indexes': [models.Index(fields=['-overall_score'], name='ai_services_overall_dd7110_idx'), models.Index(fields=['candidate'], name='ai_services_candida_c1ede1_idx'), models.Index(fields=['profile'], name='ai_services_profile_dd62e8_idx'), models.Index(fields=['-created_at'], name='ai_services_created_083418_idx')],
                'unique_together': {('candidate', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='cv_uploads/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommended_positions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analyses', to='candidates.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_analyses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ai_services_status_fe84df_idx'), models.Index(fields=['-created_at'], name='ai_services_created_111ed9_idx'), models.Index(fields=['candidate'], name='ai_services_candida_e82b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_transcription', models.TextField()),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('generated_profile_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_generations_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_generations', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ai_services_status_b3ba43_idx'), models.Index(fields=['-created_at'], name='ai_services_created_454e36_idx'), models.Index(fields=['profile'], name='ai_services_profile_f20b0e_idx')],
            },
        ),
    ]
