# Generated by Django 5.0.7 on 2025-11-04 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Habilitar/deshabilitar notificaciones por email', verbose_name='notificaciones por email')),
                ('in_app_notifications_enabled', models.BooleanField(default=True, help_text='Habilitar/deshabilitar notificaciones en la aplicación', verbose_name='notificaciones en app')),
                ('notify_evaluations', models.BooleanField(default=True, verbose_name='evaluaciones')),
                ('notify_candidates', models.BooleanField(default=True, verbose_name='candidatos')),
                ('notify_profiles', models.BooleanField(default=True, verbose_name='perfiles')),
                ('notify_system', models.BooleanField(default=True, verbose_name='sistema')),
                ('notify_reminders', models.BooleanField(default=True, verbose_name='recordatorios')),
                ('notify_alerts', models.BooleanField(default=True, verbose_name='alertas')),
                ('digest_enabled', models.BooleanField(default=False, help_text='Recibir un resumen diario en lugar de notificaciones individuales', verbose_name='resumen diario')),
                ('digest_time', models.TimeField(blank=True, help_text='Hora a la que se envía el resumen diario', null=True, verbose_name='hora del resumen')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='sonido')),
                ('desktop_notifications', models.BooleanField(default=False, verbose_name='notificaciones de escritorio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'preferencia de notificación',
                'verbose_name_plural': 'preferencias de notificación',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificador de la plantilla (ej: evaluation_assigned)', max_length=200, unique=True, verbose_name='nombre')),
                ('title', models.CharField(help_text='Título descriptivo de la plantilla', max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito de esta plantilla', verbose_name='descripción')),
                ('category', models.CharField(choices=[('evaluation', 'Evaluación'), ('candidate', 'Candidato'), ('profile', 'Perfil'), ('system', 'Sistema'), ('reminder', 'Recordatorio'), ('alert', 'Alerta')], default='system', max_length=20, verbose_name='categoría')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'Notificación en App'), ('both', 'Ambos')], default='both', max_length=10, verbose_name='tipo de notificación')),
                ('email_subject', models.CharField(blank=True, help_text='Asunto del correo. Puede usar variables: {user_name}, {evaluation_title}, etc.', max_length=255, verbose_name='asunto del email')),
                ('email_body_html', models.TextField(blank=True, help_text='Contenido HTML del email. Puede usar variables.', verbose_name='cuerpo HTML del email')),
                ('email_body_text', models.TextField(blank=True, help_text='Versión en texto plano del email (fallback)', verbose_name='cuerpo texto plano del email')),
                ('in_app_title', models.CharField(blank=True, max_length=255, verbose_name='título en app')),
                ('in_app_message', models.TextField(blank=True, verbose_name='mensaje en app')),
                ('is_active', models.BooleanField(default=True, help_text='Si la plantilla está disponible para usar', verbose_name='activa')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='prioridad')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='Lista de variables que se pueden usar en esta plantilla', verbose_name='variables disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'plantilla de notificación',
                'verbose_name_plural': 'plantillas de notificación',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='asunto del email')),
                ('email_body', models.TextField(blank=True, verbose_name='cuerpo del email')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida'), ('read', 'Leída')], default='pending', max_length=10, verbose_name='estado')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'En App'), ('both', 'Ambos')], default='in_app', max_length=10, verbose_name='tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='prioridad')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales usados para renderizar la notificación', verbose_name='datos de contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha después de la cual la notificación ya no es relevante', null=True, verbose_name='fecha de expiración')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email enviado')),
                ('email_error', models.TextField(blank=True, verbose_name='error de email')),
                ('action_url', models.URLField(blank=True, help_text='URL a la que redirige la notificación al hacer clic', verbose_name='URL de acción')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('body_text', models.TextField(verbose_name='cuerpo texto')),
                ('body_html', models.TextField(blank=True, verbose_name='cuerpo HTML')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('bounced', 'Rebotado')], default='pending', max_length=10, verbose_name='estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de apertura')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de clic')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Headers adicionales del email', verbose_name='headers')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Lista de nombres de archivos adjuntos', verbose_name='adjuntos')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification', verbose_name='notificación')),
            ],
            options={
                'verbose_name': 'log de email',
                'verbose_name_plural': 'logs de emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_d274b7_idx'), models.Index(fields=['created_at'], name='notificatio_created_eaa7a4_idx'), models.Index(fields=['status'], name='notificatio_status_18a272_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['name'], name='notificatio_name_05069a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['category', 'is_active'], name='notificatio_categor_109bef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'notification_type'], name='notificatio_status_c384cf_idx'),
        ),
    ]
